name: micro_dependency
description: "Where the dependencies are installed to be used in another service"
publish_to: 'none'
version: 0.0.3

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  logger: ^2.2.0
  dio: ^5.4.3+1
  awesome_dio_interceptor: ^1.2.0
  get_it: ^7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
